### PR TITLE
Get storybook working

### PR DESCRIPTION
**Pull request by lalexgap**
Addresses #51

### CODE REVIEW

**Comment by geoknee** [comment]
This looks good to me, @lalexgap !

I would like to understand *why* these changes fix the error in https://github.com/magmo/apps/issues/51 ? The only functional difference I can see is that `padBytes32` is now *not* used to construct the `buyIn` in `test-scenarios.ts`. And of course not needing the `wallet: ` in the store function.

Also: you do not need a review to merge this in (you may want to reinstate protection onto `master` if you have not done so already).

**Comment by kerzhner** [comment]
@lalexgap @geoknee I reinstated branch protection for `master` for required approval. Do we want to block merges if CI builds are failing?

**Comment by geoknee** [comment]
Re: CI fails blocking merges.

My vote would be for yes, we should block unless CI passes. 

Downsides: may have to wait a little longer for tests to run.
Upsides: much harder to introduce a breaking change into master.

**Comment by kerzhner** [comment]
@geoknee sounds good. Blocking on CI tests has been enabled.

**Pull request merged**
